wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717426433.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 17
      - 23
      - 37
      4: 3.12.2
      5: 0.16.6
      8:
      - 3
      - 5
      - 13
      13: windows-amd64
bs:
  desc: null
  value: 64
epochs:
  desc: null
  value: 3
lr:
  desc: null
  value: 0.0001
subset_size:
  desc: null
  value: 4000
