wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
architecture:
  desc: null
  value: SCAE
dataset:
  desc: null
  value: MNIST
epochs:
  desc: null
  value: 1
batch size:
  desc: null
  value: 32
v_th:
  desc: null
  value: 1
tau_m:
  desc: null
  value: 24. ms
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713864333.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.12.2
      5: 0.16.6
      8:
      - 3
      - 5
      - 13
      13: windows-amd64
