wandb_version: 1

program:
  desc: null
  value: main.py
method:
  desc: null
  value: grid
metric:
  desc: null
  value:
    name: final_test_loss
    goal: minimize
parameters:
  desc: null
  value:
    bs:
      values:
      - 64
    lr:
      values:
      - 0.001
      - 0.0001
      - 1.0e-05
      - 1.0e-06
    epochs:
      value: 3
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717001837.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.12.2
      5: 0.16.6
      8:
      - 3
      - 5
      13: windows-amd64
bs:
  desc: null
  value: 64
epochs:
  desc: null
  value: 3
lr:
  desc: null
  value: 0.001
